<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE5q7cDY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE5q7cDY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE5q7cDY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE5q7cDY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE5q7cDY\App_KernelDevDebugContainer([
    'container.build_hash' => 'E5q7cDY',
    'container.build_id' => '9475d5c6',
    'container.build_time' => 1601028089,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE5q7cDY');
