version: "3.7"

services:

  gateway:
    build:
      target: dev
    volumes:
      - ./node/src/public:/app/src/public:delegated
      - node_build:/app/src/public/build

  node:
    container_name: windowswap_node
    build:
      context: ./node
      target: dev
    volumes:
      - ./node/src:/app/src:delegated
      - node_build:/app/src/build
      - node_vendors:/app/src/node_modules
    networks:
      - windowswap

  server:
    build:
      context: ./server
      target: dev
      args:
        - XDEBUG_ACTIVE=${XDEBUG_ACTIVE}
    environment:
      SITE_URL: 'http://localhost:8080'
    volumes:
      - ./server/src:/app/src:delegated
      - server_uploads:/app/src/public/uploads
      - server_vendor:/app/src/vendor
      - /app/src/var

volumes:
  node_vendors:
  node_build:
  server_vendor:
  server_uploads:
