version: "3.7"

services:

  gateway:
    container_name: windowswap_gateway
    build:
      context: ./gateway
    restart: always
    ports:
      - ${HTTP_PORT}:8080
    networks:
      - windowswap

networks:
  windowswap:
    name: windowswap
    driver: bridge
