video.random:
    path: /api/video/random
    controller: App\Controller\RandomVideo::index
    methods: ['GET']

video.submit.new:
    path: /api/video/submit
    controller: App\Controller\SubmitVideo::index
    methods: ['POST']

video.submit.list:
    path: /api/video/submit
    controller: App\Controller\SubmissionList::index
    methods: ['GET']
