video.random:
    path: /api/video/random
    controller: App\Controller\RandomVideo::index
    methods: ['GET']

video.submit:
    path: /api/video/submit
    controller: App\Controller\SubmitVideo::index
    methods: ['POST']

oauth.callback:
    path: /api/oauth/callback
    controller: App\OAuth2\Controller\Consent::callback
    methods: ['GET']

oauth.refresh:
    path: /api/oauth/consent
    controller: App\OAuth2\Controller\Consent::consent
    methods: ['GET']
