video.random:
    path: /api/video/random
    controller: App\Controller\RandomVideo::index
    methods: ['GET']

video.submit:
    path: /api/video/submit
    controller: App\Controller\SubmitVideo::index
    methods: ['POST']
